using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DXApplication2.DTO;
using DXApplication2.DAO;
using DXApplication2.BUS;
using System.Data.SqlClient;

namespace DXApplication2
{
    public partial class FrmCapTaiKhoan : UserControl
    {
        CapQuyen_BUS CQ = new CapQuyen_BUS();
        public FrmCapTaiKhoan()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            //  dataGridView1.DataSource = CQ.GetList();
        }

        public void loadgriviewAC()
        {
            ketnoi kn = new ketnoi();
            SqlCommand mycm = new SqlCommand();
            mycm.Connection = kn.connsql;
            mycm.CommandText = @"select TenDangNhap,MatKhau,MANV,SDT,EMAIL,ChucVu,Quyen from ACCOUNT ";
            kn.connect();
            DataTable dt = new DataTable();
            SqlDataReader dr = mycm.ExecuteReader();
            dt.Load(dr);
            dataGridView1.DataSource = dt;
            kn.connsql.Close();
        }

        private void Quyen_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            FormMain frmMain = new FormMain();
            //     frmMain.Close();
            this.Hide();
            frmMain.Refresh();
            //  frmMain.Dispose();
        }


        private void FrmCapTaiKhoan_Load(object sender, EventArgs e)
        {
            Loadccb();
            loadgriviewAC();
            int a = dataGridView1.Rows.Count;
        }

        private void Loadccb()
        {
            string provider = @"Data Source=localhost;Initial Catalog=QL_KEODUA;Integrated Security=True";
            SqlConnection connect = new SqlConnection(provider);
            DataSet ds = new DataSet();
            string CauLenh = "SELECT DISTINCT ChucVu FROM ACCOUNT";
            SqlDataAdapter da = new SqlDataAdapter(CauLenh, provider);
            da.Fill(ds, "ACCOUNT");
            comboBox1.DataSource = ds.Tables[0];
            comboBox1.DisplayMember = "ChucVu";
            comboBox1.ValueMember = "ChucVu";

            DataSet ds1 = new DataSet();
            string CauLenh1 = "SELECT DISTINCT Quyen FROM ACCOUNT";
            SqlDataAdapter da1 = new SqlDataAdapter(CauLenh1, provider);
            da1.Fill(ds1, "ACCOUNT");
            comboBox2.DataSource = ds1.Tables[0];
            comboBox2.DisplayMember = "Quyen";
            comboBox2.ValueMember = "Quyen";
        }

        private void suathongtin()
        {
            try
            {
                ketnoi kn = new ketnoi();
                SqlCommand mycm = new SqlCommand();
                mycm.Connection = kn.connsql;
                mycm.CommandText = "exec suaaccount @tendn,@matkhau,@manv,@sdt,@Email,@chucvu,@quyen";
                mycm.Parameters.Add("@tendn", SqlDbType.VarChar, 30).Value = textBox1.Text;
                mycm.Parameters.Add("@matkhau", SqlDbType.VarChar, 30).Value = textBox2.Text;
                mycm.Parameters.Add("@manv", SqlDbType.VarChar, 30).Value = textBox3.Text;
                mycm.Parameters.Add("@sdt", SqlDbType.VarChar, 30).Value = textBox4.Text;
                mycm.Parameters.Add("@Email", SqlDbType.VarChar, 30).Value = textBox5.Text;
                mycm.Parameters.Add("@chucvu", SqlDbType.NVarChar, 30).Value = comboBox1.Text;
                mycm.Parameters.Add("@quyen", SqlDbType.Int).Value = comboBox2.Text;
                kn.connect();
                int kq = mycm.ExecuteNonQuery();
                if (kq > 0)
                {
                    loadgriviewAC();
                }
                else
                {

                }
                kn.connsql.Close();
                MessageBox.Show("Đã sửa thông tin và quyền Account " + textBox1.Text + "!!");
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void btnCQ_Click(object sender, EventArgs e)
        {
            suathongtin();
        }

        public void xoataikhoan()
        {
            try
            {
                ketnoi kn = new ketnoi();
                SqlCommand mycm = new SqlCommand();
                mycm.Connection = kn.connsql;
                mycm.CommandText = "exec xoaaccount @tendn";
                mycm.Parameters.Add("@tendn", SqlDbType.VarChar, 30).Value = textBox1.Text;
                kn.connect();
                int kq = mycm.ExecuteNonQuery();
                if (kq > 0)
                {
                    loadgriviewAC();
                }
                else
                {

                }
                kn.connsql.Close();
                MessageBox.Show("Đã Xóa Tài Khoản " + textBox1.Text + "!!");
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void ButtonXoa_Click(object sender, EventArgs e)
        {
            xoataikhoan();
        }

        private void ButtonThem_Click(object sender, EventArgs e)
        {
            try
            {
            ketnoi kn = new ketnoi();
            SqlCommand mycm = new SqlCommand();
            mycm.Connection = kn.connsql;
            mycm.CommandText = "exec themaccount @tendn,@matkhau,@mannv,@sdt,@Email,@chucvu,@quyen";
            mycm.Parameters.Add("@tendn", SqlDbType.VarChar, 30).Value = textBox1.Text;
            mycm.Parameters.Add("@matkhau", SqlDbType.VarChar, 30).Value = textBox2.Text;
            mycm.Parameters.Add("@mannv", SqlDbType.VarChar, 30).Value = textBox3.Text;
            mycm.Parameters.Add("@sdt", SqlDbType.VarChar, 30).Value = textBox4.Text;
            mycm.Parameters.Add("@Email", SqlDbType.VarChar, 30).Value = textBox5.Text;
            mycm.Parameters.Add("@chucvu", SqlDbType.NVarChar, 30).Value = comboBox1.Text;
            mycm.Parameters.Add("@quyen", SqlDbType.Int).Value = comboBox2.Text;
            kn.connect();
            int kq = mycm.ExecuteNonQuery();
            if (kq > 0)
            {
                loadgriviewAC();
            }
            else
            {
            }
            kn.connsql.Close();
            MessageBox.Show("Đã thêm account " + textBox1.Text + "!!");
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void dataGridView1_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            int d = e.RowIndex;
            textBox1.Text = dataGridView1.Rows[d].Cells[0].Value.ToString();
            textBox2.Text = dataGridView1.Rows[d].Cells[1].Value.ToString();
            textBox3.Text = dataGridView1.Rows[d].Cells[2].Value.ToString();
            textBox4.Text = dataGridView1.Rows[d].Cells[3].Value.ToString();
            textBox5.Text = dataGridView1.Rows[d].Cells[4].Value.ToString();
            comboBox1.Text = dataGridView1.Rows[d].Cells[5].Value.ToString();
            comboBox2.Text = dataGridView1.Rows[d].Cells[6].Value.ToString();            
        }
    }
}
