//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBKEODUA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTDONHANGs = new HashSet<CTDONHANG>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string MALOAISP { get; set; }
        public string TRONGLUONG { get; set; }
        public string QUYCACH { get; set; }
        public string KHUYENMAI { get; set; }
        public Nullable<int> GIABAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONHANG> CTDONHANGs { get; set; }
        public virtual CTSANPHAM CTSANPHAM { get; set; }
        public virtual LOAISP LOAISP { get; set; }
    }
}
